baseurl = "http://tomhelmer.github.io"
languageCode = "en-us"
title = "Thehome"

description = "My site"

[indexes]
    category = "categories"
    tag = "tags"

[params]
    logo = "<i class=\"fa fa-home\"></i>"
    cdnprefix = "http://res.cloudinary.com/thehome-dk/image/upload"

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"

[[menu.main]]
  name = "Articles"
  identifier = "articles"
  url = "/article"
  weight = 1
